# Light component analysis

In [1]:
from pylab import *

In [13]:
m_p = 0.938 # Proton mass

In [22]:
Z = 1 # Atomic number
A = 1 # Mass number
n = 1 # Number of nucleons in H

data_PAMELA_H = np.genfromtxt("Data/Proton/PAMELA_H_data.txt")
R_PAMELA = data_PAMELA_H[:,1]
E_PAMELA_H = (R_PAMELA * Z) - (A * m_p)
flux_R_PAMELA = data_PAMELA_H[:,3]
flux_PAMELA_H = flux_R_PAMELA * (R_PAMELA / ((Z * R_PAMELA) - (A * m_p))) # Normalize to Ek
error_PAMELA_stat = data_PAMELA_H[:,4] * (R_PAMELA / ((Z * R_PAMELA) - (A * m_p))) # Normalize to Ek
error_PAMELA_syst = data_PAMELA_H[:,5] * (R_PAMELA / ((Z * R_PAMELA) - (A * m_p))) # Normalize to Ek
error_PAMELA_H = np.sqrt(error_PAMELA_stat**2 + error_PAMELA_syst**2) 

R_PAMELA

array([1.01000e+00, 1.06000e+00, 1.11000e+00, 1.16000e+00, 1.22000e+00,
       1.28000e+00, 1.34000e+00, 1.40000e+00, 1.47000e+00, 1.54000e+00,
       1.61000e+00, 1.68000e+00, 1.76000e+00, 1.85000e+00, 1.93000e+00,
       2.02000e+00, 2.12000e+00, 2.22000e+00, 2.32000e+00, 2.43000e+00,
       2.55000e+00, 2.67000e+00, 2.79000e+00, 2.92000e+00, 3.06000e+00,
       3.21000e+00, 3.36000e+00, 3.52000e+00, 3.68000e+00, 3.86000e+00,
       4.04000e+00, 4.23000e+00, 4.43000e+00, 4.74000e+00, 5.20000e+00,
       5.70000e+00, 6.25000e+00, 6.86000e+00, 7.52000e+00, 8.24000e+00,
       9.04000e+00, 9.91000e+00, 1.08600e+01, 1.19100e+01, 1.30600e+01,
       1.43200e+01, 1.57000e+01, 1.72200e+01, 1.88800e+01, 2.07000e+01,
       2.27000e+01, 2.48900e+01, 2.72900e+01, 2.99200e+01, 3.28100e+01,
       3.59700e+01, 3.94400e+01, 4.32500e+01, 4.74200e+01, 5.20000e+01,
       5.70100e+01, 6.25100e+01, 6.85400e+01, 7.51600e+01, 8.24100e+01,
       9.03600e+01, 1.01340e+02, 1.16360e+02, 1.33600e+02, 1.533

In [23]:
Z = 2 # Atomic number
A = 4 # Mass number
n = 4 # Number of nucleons in H

data_PAMELA_He = np.genfromtxt("Data/Helium/PAMELA_He_data.txt")
R_PAMELA = data_PAMELA_He[:,1]
E_PAMELA_He = (R_PAMELA * Z) - (A * m_p)
flux_R_PAMELA = data_PAMELA_He[:,3]
flux_PAMELA_H = flux_R_PAMELA * (R_PAMELA / ((Z * R_PAMELA) - (A * m_p))) # Normalize to Ek
error_PAMELA_stat = data_PAMELA_He[:,4] * (R_PAMELA / ((Z * R_PAMELA) - (A * m_p))) # Normalize to Ek
error_PAMELA_syst = data_PAMELA_He[:,5] * (R_PAMELA / ((Z * R_PAMELA) - (A * m_p))) # Normalize to Ek
error_PAMELA_He = np.sqrt(error_PAMELA_stat**2 + error_PAMELA_syst**2) 

R_PAMELA

array([1.01000e+00, 1.06000e+00, 1.11000e+00, 1.16000e+00, 1.22000e+00,
       1.27000e+00, 1.33000e+00, 1.40000e+00, 1.46000e+00, 1.53000e+00,
       1.60000e+00, 1.68000e+00, 1.76000e+00, 1.84000e+00, 1.93000e+00,
       2.02000e+00, 2.11000e+00, 2.21000e+00, 2.32000e+00, 2.43000e+00,
       2.54000e+00, 2.66000e+00, 2.79000e+00, 2.92000e+00, 3.06000e+00,
       3.20000e+00, 3.35000e+00, 3.51000e+00, 3.67000e+00, 3.85000e+00,
       4.03000e+00, 4.22000e+00, 4.42000e+00, 4.63000e+00, 4.85000e+00,
       5.07000e+00, 5.44000e+00, 5.96000e+00, 6.54000e+00, 7.17000e+00,
       7.86000e+00, 8.62000e+00, 9.45000e+00, 1.03700e+01, 1.13700e+01,
       1.24600e+01, 1.36700e+01, 1.49900e+01, 1.64300e+01, 1.80200e+01,
       1.97600e+01, 2.16700e+01, 2.37600e+01, 2.60500e+01, 2.85600e+01,
       3.13200e+01, 3.43400e+01, 3.76600e+01, 4.12900e+01, 4.52800e+01,
       4.96400e+01, 5.44400e+01, 5.96900e+01, 6.54500e+01, 7.17600e+01,
       7.86900e+01, 8.62800e+01, 9.46000e+01, 1.06110e+02, 1.218

In [20]:
E_PAMELA_H

array([7.200000e-02, 1.220000e-01, 1.720000e-01, 2.220000e-01,
       2.820000e-01, 3.420000e-01, 4.020000e-01, 4.620000e-01,
       5.320000e-01, 6.020000e-01, 6.720000e-01, 7.420000e-01,
       8.220000e-01, 9.120000e-01, 9.920000e-01, 1.082000e+00,
       1.182000e+00, 1.282000e+00, 1.382000e+00, 1.492000e+00,
       1.612000e+00, 1.732000e+00, 1.852000e+00, 1.982000e+00,
       2.122000e+00, 2.272000e+00, 2.422000e+00, 2.582000e+00,
       2.742000e+00, 2.922000e+00, 3.102000e+00, 3.292000e+00,
       3.492000e+00, 3.802000e+00, 4.262000e+00, 4.762000e+00,
       5.312000e+00, 5.922000e+00, 6.582000e+00, 7.302000e+00,
       8.102000e+00, 8.972000e+00, 9.922000e+00, 1.097200e+01,
       1.212200e+01, 1.338200e+01, 1.476200e+01, 1.628200e+01,
       1.794200e+01, 1.976200e+01, 2.176200e+01, 2.395200e+01,
       2.635200e+01, 2.898200e+01, 3.187200e+01, 3.503200e+01,
       3.850200e+01, 4.231200e+01, 4.648200e+01, 5.106200e+01,
       5.607200e+01, 6.157200e+01, 6.760200e+01, 7.4222

In [21]:
E_PAMELA_He

array([-1.732000e+00, -1.632000e+00, -1.532000e+00, -1.432000e+00,
       -1.312000e+00, -1.212000e+00, -1.092000e+00, -9.520000e-01,
       -8.320000e-01, -6.920000e-01, -5.520000e-01, -3.920000e-01,
       -2.320000e-01, -7.200000e-02,  1.080000e-01,  2.880000e-01,
        4.680000e-01,  6.680000e-01,  8.880000e-01,  1.108000e+00,
        1.328000e+00,  1.568000e+00,  1.828000e+00,  2.088000e+00,
        2.368000e+00,  2.648000e+00,  2.948000e+00,  3.268000e+00,
        3.588000e+00,  3.948000e+00,  4.308000e+00,  4.688000e+00,
        5.088000e+00,  5.508000e+00,  5.948000e+00,  6.388000e+00,
        7.128000e+00,  8.168000e+00,  9.328000e+00,  1.058800e+01,
        1.196800e+01,  1.348800e+01,  1.514800e+01,  1.698800e+01,
        1.898800e+01,  2.116800e+01,  2.358800e+01,  2.622800e+01,
        2.910800e+01,  3.228800e+01,  3.576800e+01,  3.958800e+01,
        4.376800e+01,  4.834800e+01,  5.336800e+01,  5.888800e+01,
        6.492800e+01,  7.156800e+01,  7.882800e+01,  8.680800e